Implemented Comments part 1
sublinks/sublinks-frontend pull request #34
Opened 2023-12-29 21:53 UTC by Pdzly

Implemented Comments ( Upvotes, Downvotes )

Not implemented: 

Replies
More options button

2023-12-30 21:10 UTC, kgilles requested changes
This is great stuff! Appreciate the work you're putting into the project!

2023-12-30 21:10 UTC, kgilles commented on src/components/comment/index.tsx
> +            <Markdown className="text-gray-600 dark:text-gray-200 text-sm max-md:hidden line-clamp-2 group-visited:text-gray-500 group-visited:dark:text-gray-400">
Group classes only work if a parent element is marked as group. See how it's done in the `Post` component for example.

Although I don't think we want to lighten the entire comment body if a user has visited the comment link before. So we could likely remove the group classes instead.

2023-12-30 21:10 UTC, kgilles commented on src/components/comment/index.tsx
> +              {content}
No comment content shows up when in mobile.
![image](https://github.com/sublinks/sublinks-frontend/assets/2633655/6dcc86ac-3829-4fc8-bac4-1a6b533b5647)

2023-12-30 21:10 UTC, kgilles commented on src/components/person-comments-posts/index.tsx
>    return (
This didn't come from this PR, but when taking a closer look at these tabs in dark mode the colors makes the selected tab look unselected and vice versa.

Perhaps it's just me. What do you think? Here "Posts" is selected but "Comments" has a darker color which makes me think "Comments" is the currently active tab.
![image](https://github.com/sublinks/sublinks-frontend/assets/2633655/73f714a5-c233-4992-ba66-41b6b03f3532)

2023-12-31 15:10 UTC, Pdzly commented on src/components/comment-votes/index.tsx
They act not the same 100%, Comment votes stays down, post votes stays on the left and then on smaller screens it moves to the same position as the comment vote

2023-12-31 15:11 UTC, Pdzly commented on src/components/icon/index.tsx
> +  SvgClassName?: string;
Did you notice it doesnt work? Those are svg icons not font icons!

2023-12-31 15:16 UTC, Pdzly commented on src/components/linkbutton/index.tsx
I will do button-link as like you said its better visible

2023-12-31 15:16 UTC, Pdzly commented on src/components/text/index.tsx
> +const SmallerBodyText = ({ children, className, title }: TextProps) => <span className={cx('text-sm text-gray-600 dark:text-gray-200', className)} title={title}>{children}</span>;
Oki

2023-12-31 15:21 UTC, Pdzly commented on src/components/comment-header/index.tsx
> +  ap_id: string;
Ok, ap_id is the federated link to the comment. I would keep it like so, or otherwise someone will say what is xyz ? Follows the trace up to the fetchpoint and says "Ahhh its the ap_id".

2023-12-31 15:22 UTC, Pdzly commented on src/components/comment-header/index.tsx
> +      {updated && <Icon IconType={PencilIcon} size={ICON_SIZE.VERYSMALL} className="ml-4" />}
Yeah i could see that too. Will try if edited looks good othwise just an asterisk.l

2023-12-31 15:30 UTC, Pdzly commented on src/components/comment-header/index.tsx
> +      {updated && <Icon IconType={PencilIcon} size={ICON_SIZE.VERYSMALL} className="ml-4" />}
(See matrix)

2023-12-31 15:32 UTC, Pdzly commented on src/components/comment-header/index.tsx
> +  ap_id: string;
i would rename it to apId to make it ESLint compatible but i would still keep it.

2023-12-31 15:36 UTC, Pdzly commented on src/components/person-comments-posts/index.tsx
>    return (
![image](https://github.com/sublinks/sublinks-frontend/assets/34943569/ef110354-d0d5-4bdb-9322-bd0f8396548c)

2023-12-31 15:37 UTC, Pdzly commented on src/components/person-comments-posts/index.tsx
>    return (
I changed it like this, ( The dark part IS selected now )

2023-12-31 15:38 UTC, Pdzly commented on src/components/comment/index.tsx
> +              {content}
Fixed was just a oversight on my side!

2024-01-02 15:13 UTC, kgilles commented on src/components/comment-votes/index.tsx
I was thinking more about how they function. Ie. allowing (dis)liking a post or comment and being highlighted if the user has already voted. Even still these design differences you mentioned are minor. The only difference in code I can see between the two is whether we set the `flex-col` or `flex-row` class on it.

2024-01-02 15:18 UTC, kgilles commented on src/components/icon/index.tsx
> +  SvgClassName?: string;
This works just fine for me.
```
<Icon IconType={ArrowUpIcon} size={ICON_SIZE.SMALL} className={`hover:text-blue-400 ${myVote === 1 && 'text-blue-600'}`} />
```

> And i would keep it as so, when we want to change the div in the background.

If we want to change the background color we'll just use a `bg-` class. It won't interfere with the SVG.

2024-01-02 15:30 UTC, kgilles commented on src/components/comment-header/index.tsx
> +  ap_id: string;
I'm sure you and all of the Lemmy World devs know what it stands for. But "ap ID" means nothing to people who haven't worked in Lemmy, like myself.

> or otherwise someone will say what is xyz ?

Not if we give it an actual useful name. Like `commentUrl` based on your own description of it as "ap_id is the federated link to the comment".

But if you really want it to say `apId` then let's keep it for now. Hopefully Sublinks backend will give us better property names when they build out the non-Lemmy API.

2024-01-02 15:35 UTC, kgilles approved these changes

2024-01-02 17:09 UTC, lazyguru commented on src/components/comment-header/index.tsx
> +  ap_id: string;
Just my 2 cents, let's all remember we are not copying Lemmy. We are replacing it. We need to be compatible ONLY on the API and federation side. We don't need to be compatible on the frontend (sublinks-frontend is intended only for use with Sublinks, not with Lemmy). So we don't need to keep ap_id. We can use something that makes more logic sense in the context it is being used)

2024-01-02 17:17 UTC, Pdzly commented on src/components/icon/index.tsx
> +  SvgClassName?: string;
hmm then on firefox this doesnt work. ( or just on my side )

2024-01-02 17:19 UTC, Pdzly commented on src/components/comment-header/index.tsx
> +  ap_id: string;
Yeah i know, but until we dont have the api its more clearer to have the same naming what the api returns. ( for now )

2024-01-02 18:03 UTC, Pdzly commented on src/components/icon/index.tsx
> +  SvgClassName?: string;
Yep it does NOT work on firefox and its probably just a sideeffect of chromes svg implementation.

Because of this i would propose to stay what i done for firefox compatibility

2024-01-02 20:31 UTC, kgilles commented on src/components/post/index.tsx
> +'use client';
Rather than making the parent components of `VoteButtons` client-side, could we move the like/dislike logic into it? I don't think we would expect to do anything other than calling the `likeComment` API function when an arrow is clicked. All it would need to know is the entity ID and whether it's a post or a comment that's being voted on.

2024-01-02 20:31 UTC, kgilles commented on src/components/button-votes/index.tsx
> +  <div className={cx('flex flex-row justify-center items-center', {
Can remove `flex-row` from the default classes.

2024-01-03 08:49 UTC, Pdzly commented on src/components/button-votes/index.tsx
> +  <div className={cx('flex flex-row justify-center items-center', {
Yeh

2024-01-03 08:51 UTC, Pdzly commented on src/components/post/index.tsx
> +'use client';
And likePost + in the future invalidate cache and refetch that post

2024-01-03 15:17 UTC, kgilles approved these changes

2024-01-03 17:16 UTC, kgilles approved these changes

2024-01-03 21:51 UTC, merged