Added Some
sublinks/sublinks-frontend pull request #4
Opened 2023-12-12 14:37 UTC by Pdzly

2023-12-12 16:10 UTC, kgilles requested changes
Great progress!

Perhaps you'd already planned for this but make sure the page and components look good in mobile and other generally smaller screens.

There's also some dark text on dark background when using dark mode that also needs updated.

2023-12-12 16:10 UTC, kgilles commented on src/app/user/page.tsx
> +        <ModeratesList moderates={testData.moderates as any} />
`any` is not an allowed type. Please be more specific.

2023-12-12 16:10 UTC, kgilles commented on src/components/moderates-list/index.tsx
> +  <div className="flex gap-12 relative center items-center" onClick={() => {
Using `div` with an onClick handler can provide poor accessibility. It's recommended to use semantic HTML instead, ie. a `button`.

But also, If this click handler only directs the user to a URL then a link element should be used instead. That way we don't need this component to be client-side either.

2023-12-12 16:10 UTC, kgilles commented on src/components/moderates-list/index.tsx
> +    <h1 className="text-2xl font-bold mb-4 border-collapse border-b dark:border-gray-400 border-gray-800 ">Moderates:</h1>
We have a homemade `H1` component under components/text that I would appreciate we re-use here for consistency.

2023-12-12 16:10 UTC, kgilles commented on src/components/moderates-list/index.tsx
> +        <div key={moderate.community.actor_id} className="border-b border-spacing dark:border-gray-50 border-gray-400 my-2 min-h-[35px] relative p-2 border-collapse cursor-pointer">
> min-h-[35px]

Please don't use custom sizes unless absolutely necessary.

2023-12-12 16:10 UTC, kgilles commented on src/components/person-detail/index.tsx
> +const customMarkdownComponents: Components = {
If we're re-using the markdown configuration then we'd do better breaking it out into a standalone component or util. To make sure we can use the same configuration everywhere without having to rewrite it.

2023-12-12 16:10 UTC, kgilles commented on src/components/person-detail/index.tsx
> +    {is_admin ? (
How many different badges exist? This could be a good candidate for a standalone "Badge" component.
Doesn't have to happen in this PR, but a project task could be created to make them all.

2023-12-12 16:10 UTC, kgilles commented on src/components/person-detail/index.tsx
> +    <div className="text-gray-600 dark:text-gray-200 text-2xl ">
Use homemade text components when possible. If none exist that matches what you want feel free to create a new text component under components/text

2023-12-13 14:59 UTC, Pdzly commented on src/app/user/page.tsx
> +        <ModeratesList moderates={testData.moderates as any} />
Would have done it, if the test data wasnt annoying. Final would be to use the Interface sublink-js exports

2023-12-13 15:07 UTC, Pdzly commented on src/components/moderates-list/index.tsx
> +        <div key={moderate.community.actor_id} className="border-b border-spacing dark:border-gray-50 border-gray-400 my-2 min-h-[35px] relative p-2 border-collapse cursor-pointer">
Would have used it if min-h- had anything in px min-h-0 or min-h-full is only the real available thing

2023-12-13 15:07 UTC, Pdzly commented on src/components/person-detail/index.tsx
> +    {is_admin ? (
Only one

2023-12-13 15:20 UTC, Pdzly commented on src/components/moderates-list/index.tsx
> +    <h1 className="text-2xl font-bold mb-4 border-collapse border-b dark:border-gray-400 border-gray-800 ">Moderates:</h1>
Thanks! i didnt saw that until now! Sorry!

2023-12-13 15:21 UTC, Pdzly commented on src/components/person-detail/index.tsx
> +    {is_admin ? (
Only one for Profile BUT 2 for moderator. Hmmm i think we can reuse that component on the comment / posts too!

2023-12-13 15:21 UTC, Pdzly commented on src/components/person-detail/index.tsx
> +    <div className="text-gray-600 dark:text-gray-200 text-2xl ">
Done!

2023-12-13 19:28 UTC, kgilles commented on src/components/person-detail/index.tsx
> +    {is_admin ? (
I like that idea

2023-12-13 19:31 UTC, kgilles commented on src/components/moderates-list/index.tsx
> +        <div key={moderate.community.actor_id} className="border-b border-spacing dark:border-gray-50 border-gray-400 my-2 min-h-[35px] relative p-2 border-collapse cursor-pointer">
You're right. I missed that when setting up the config. If you wanna go ahead and add this to the tailwind config then you'll have min-x options:

```
minHeight: {
  ...spacing,
  full: '100%'
},
minWidth: {
  ...spacing,
  full: '100%'
},
```

2023-12-13 19:32 UTC, kgilles commented on src/app/user/page.tsx
> +        <ModeratesList moderates={testData.moderates as any} />
Rather than using `any` you can export the expected prop type interface from `src\components\moderates-list\index.tsx` and then re-use it here.

2023-12-13 19:40 UTC, kgilles requested changes
Mobile view is quite crowded horizontally with the moderates list. I'd recommend giving the user page a more column-like flow of components. Since the horizontal viewport is usually narrow in smaller devices.

![image](https://github.com/sublinks/frontend/assets/2633655/ecd95777-9d0c-4891-aa91-e53f4f8a04b3)

2023-12-13 19:40 UTC, kgilles commented on src/app/user/page.tsx
> +    <PersonDetailSelection posts={testData.posts as any} comments={testData.comments as any} />
Same ask about these `any`

2023-12-13 19:40 UTC, kgilles commented on src/utils/TailwindMaterial.ts
> +"use client";
Is this util required to be client side?

2023-12-13 19:40 UTC, kgilles commented on tailwind.config.ts
> +    "path-to-your-node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}",
These paths are invalid. I presume "path-to-your-node_modules" should be updated to match our structure.

2023-12-13 20:55 UTC, Pdzly commented on src/utils/TailwindMaterial.ts
> +"use client";
Yep since Nextjs 13

2023-12-13 20:56 UTC, Pdzly commented on tailwind.config.ts
> +    "path-to-your-node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}",
ahh yeh

2023-12-14 02:29 UTC, kgilles commented on src/utils/TailwindMaterial.ts
> +"use client";
Oh, I see now. I was confused by the import-export being under `util`. Since these are actual components I think they'd fit better under `components`.

2023-12-14 02:37 UTC, kgilles requested changes
Just one or two more minor things. Patch those up, move this PR out of draft mode and I'll approve things when I wake up tomorrow.

2023-12-14 02:37 UTC, kgilles commented on src/components/person-comments-posts/index.tsx
> +          <TabPanel key={value} value={value} className="">
Empty `classname` can be removed

2023-12-14 15:10 UTC, Pdzly commented on src/utils/TailwindMaterial.ts
> +"use client";
ok

2023-12-14 15:10 UTC, Pdzly commented on src/components/person-comments-posts/index.tsx
> +          <TabPanel key={value} value={value} className="">
Yep forgot sorry!

2023-12-14 18:06 UTC, kgilles requested changes

2023-12-14 18:06 UTC, kgilles commented on src/components/post-header/index.tsx
> -'use client';
This component needs to be client-side still as it's using `useState`

2023-12-14 18:33 UTC, kgilles approved these changes

2023-12-14 18:33 UTC, merged