Added Post Sort and Type action buttons
sublinks/sublinks-frontend pull request #40
Opened 2024-01-03 21:59 UTC by Pdzly

2024-01-04 03:45 UTC, kgilles requested changes
![image](https://github.com/sublinks/sublinks-frontend/assets/2633655/7ca292a1-b50e-4cb2-817f-052735792f6b)

Options don't render nicely in mobile.

2024-01-04 03:45 UTC, kgilles commented on .eslintrc.json
> +    "react/jsx-props-no-spreading": "off"
I'd prefer we keep this rule enabled. eslint [explains](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md) it well what good it does:
> This enhances readability of code by being more explicit about what props are received by the component. It is also good for maintainability by avoiding passing unintentional extra props and allowing react to emit warnings when invalid HTML props are passed to HTML elements.

2024-01-04 03:45 UTC, kgilles commented on src/components/post-feed-sort/index.tsx
> +    <Option value="Active" selected={currentSort === 'Active'}>Active</Option>
React uses `value` on the select component rather than `selected` on option. This warning is being thrown in the console:
```
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
```

2024-01-04 03:45 UTC, kgilles commented on src/app/page.tsx
> +'use client';
Making the page a client component this high up in the hierarchy prevents us from fetching the initial posts server-side. We should keep this `page.tsx` server-side and instead have `PostFeed` fetch data client-side when options change. Or create a new component between the two to handle client-side stuff.

2024-01-04 03:45 UTC, kgilles commented on src/app/page.tsx
> +    testData as unknown as GetPostsResponse
Having `testData` be the default value prevents us from testing this properly with Docker where we only want data from the API and DB. It should only default to `testData` if we don't have `SUBLINKS_API_BASE_URL`.

2024-01-04 03:45 UTC, kgilles commented on src/components/post-feed-sort/index.tsx
> +    <Button id="post-feed-type-all" type="button" onClick={() => onTypeChange('All')} className={`${currentType === 'All' ? 'bg-blue-300 dark:bg-blue-500' : 'bg-gray-200 dark:bg-gray-400'} ${buttonGr
Do you think it'd be possible to move this class logic into the Button component itself? And instead use a prop like `active={currentType === 'All'}` or something here?

That way we'd hopefully not have to repeat it for each button.

2024-01-04 03:45 UTC, kgilles commented on src/components/post-feed-sort/index.tsx
> +    <Option value="Scaled" selected={currentSort === 'Scaled'}>Scaled</Option>
These Options could be simplified to prevent repeating each property like this. For example:

```
// Place this somewhere near the top of the file or even in a separate file
const options = [
  {
    label: 'Hot',
    value: 'Hot'
  },
  {
    label: 'Top Hour',
    value: 'TopHour'
  },
  {...}
];

// Then iterate over them to create each option
{options.map(option => <Option key={option.value} value={option.value}>{option.label}</Option>)}
```

2024-01-04 03:45 UTC, kgilles commented on src/components/post-feed-sort/index.tsx
> +  currentType?: ListingType
I would expect the type and sort options to always have a value. But maybe that's something we update later on.

2024-01-04 15:36 UTC, Pdzly commented on src/components/post-feed-sort/index.tsx
> +    <Option value="Active" selected={currentSort === 'Active'}>Active</Option>
Ahh ok

2024-01-04 15:57 UTC, Pdzly commented on src/components/post-feed-sort/index.tsx
> +    <Option value="Scaled" selected={currentSort === 'Scaled'}>Scaled</Option>
Yeah forgot it would be done so. I just dont like it that the library is not an enum rather just a type. Othwise we could just use the enum to enumerate it.

2024-01-04 16:01 UTC, Pdzly commented on src/components/post-feed-sort/index.tsx
> +  currentType?: ListingType
We need to update it later on. As we need to fetch the users options and then select their prefered option.

2024-01-07 03:54 UTC, kgilles requested changes
Nice work updating the feed to be server-side again.

Left a few more comments for final polish. Let me know when you made changes and I'll give you a quick ✅

2024-01-07 03:54 UTC, kgilles commented on src/components/button/index.tsx
> +  type: 'button' | 'submit' | 'reset' | undefined;
`type` should never be undefined. And it doesn't look like it ever is when using this component so I don't think we actually need this option(?)

2024-01-07 03:54 UTC, kgilles commented on src/components/front-page-feed/index.tsx
> +  // @todo: Allow test data when in non-docker dev env
Comment can be removed or moved down to the useEffect where it's more relevant

2024-01-07 03:54 UTC, kgilles commented on src/components/front-page-feed/index.tsx
> +      <PostFeed data={postFeed?.posts || []} />
We don't need the optional chaining here as `postFeed` should never be undefined based on typings

2024-01-07 20:30 UTC, Pdzly commented on src/components/button/index.tsx
> +  type: 'button' | 'submit' | 'reset' | undefined;
I did it because the type of a buttons "type" is like this.

2024-01-07 20:30 UTC, Pdzly commented on src/components/front-page-feed/index.tsx
> +  // @todo: Allow test data when in non-docker dev env
Ok

2024-01-07 20:31 UTC, Pdzly commented on src/components/front-page-feed/index.tsx
> +      <PostFeed data={postFeed?.posts || []} />
But it is theoretically. In the first run of the script the state is empty. Only after few seconds and after the useeffect triggered it isnt undefined

2024-01-07 21:12 UTC, kgilles commented on src/components/front-page-feed/index.tsx
> +      <PostFeed data={postFeed?.posts || []} />
It's not empty since the initial `posts` property that we send to this component is populated on the server. We shouldn't need to fetch any posts unless the user changes either feed option. That's another note for the `useEffect` logic btw: To not have it make a request on mount. If you want to do this in the same PR feel free. If not I can look at it later.

Main problem is probably around the fact that `posts` is being sent in as a string rather than an object. You said it didn't work without it, but rendering `<Feed posts={posts} />` works just fine for me. Even when I comment out the `useEffect` to make sure no client-side data fetch is happening.

I recommend you try this with the Docker setup if you haven't yet.

2024-01-07 21:15 UTC, kgilles commented on src/components/button/index.tsx
> +  type: 'button' | 'submit' | 'reset' | undefined;
That makes sense. But we/I don't want to allow undefined button type because it may default to "submit" which isn't always the expected value.

Explanation from the eslint rule:

> The default value of type attribute for button HTML element is "submit" which is often not the desired behavior and may lead to unexpected page reloads. This rules enforces an explicit type attribute for all the button elements and checks that its value is valid per spec (i.e., is one of "button", "submit", and "reset").

2024-01-09 14:51 UTC, kgilles approved these changes

2024-01-09 14:51 UTC, merged