Implemented the side bar
sublinks/sublinks-frontend pull request #53
Opened 2024-01-20 12:28 UTC by Pdzly

Implemented the sidebar and made that the api url is available in clientside components.

2024-01-20 16:12 UTC, kgilles requested changes

2024-01-20 16:12 UTC, kgilles commented on src/components/sidebar-siteinfo/index.tsx
> +      <Collapsable open={adminOpen} onSwitch={setAdminOpen} title="Admins" contentClassName="flex flex-row" containerClassName="border-t border-gray-500" showIcon>
All occurrences of `Collapsable` have the same content and container class names. Perhaps we could makes these class names the default in the component instead of having to specify them each time?

Same for `showIcon`

2024-01-20 16:12 UTC, kgilles commented on src/components/collapsable/index.tsx
> +  const [active, setActive] = useState(open !== undefined ? open : false);
No need to check whether `open` is undefined. We can use it as the default value here: `useState(open);`

2024-01-20 16:12 UTC, kgilles commented on src/components/collapsable/index.tsx
> +    if (onSwitch) {
I would recommend, instead of having two ways of controlling the open state, we only use one to keep things clean.
Ie. get rid of the "active" component state and just rely on the incoming `open` and `onSwitch` props.

2024-01-20 16:12 UTC, kgilles commented on src/components/collapsable/index.tsx
> +  buttonClassName?: string;
The `buttonClassName` is not used and can be removed

2024-01-20 16:12 UTC, kgilles commented on src/components/collapsable/index.tsx
> +        <ChevronUpIcon
There's a chevron down icon we can use rather than rotating the up-version.

2024-01-20 16:12 UTC, kgilles commented on src/components/sidebar/index.tsx
> +  open?: boolean;
This prop is never sent to this component. Can be removed.
Same with `onSwitch`.

2024-01-20 16:12 UTC, kgilles commented on src/components/sidebar/index.tsx
> +        <Icon className="bg-none" IconType={hidden ? ChevronLeftIcon : ChevronRightIcon} size={ICON_SIZE.MEDIUM} />
Class `bg-none` doesn't do anything as the icon is already transparent(?)

2024-01-20 16:14 UTC, kgilles commented
Having the sidebar at the top of the screen when in mobile uses valuable screen real estate. Even when closed. I'd recommend we place a trigger to open it next to the sorting options instead.

![image](https://github.com/sublinks/sublinks-frontend/assets/2633655/eadeeb34-7b8f-4e2e-8bb4-513c97f222a3)

2024-01-20 16:15 UTC, kgilles commented
When the sidebar is open in mobile I'd like to see a button to close the entire thing at the top of the component. So I can just click an X or something to collapse it. Rather than having to collapse each section separately to the very bottom of the sidebar.

![image](https://github.com/sublinks/sublinks-frontend/assets/2633655/6a78e33c-26d8-4d3c-86c6-4908b7c22dcd)

2024-01-20 18:07 UTC, Pdzly commented on src/components/sidebar/index.tsx
> +        <Icon className="bg-none" IconType={hidden ? ChevronLeftIcon : ChevronRightIcon} size={ICON_SIZE.MEDIUM} />
Sorry was a leftover of an bg issue i had.

2024-01-21 10:16 UTC, Pdzly commented on etc/dev/docker-compose.dev.yml
> +      - "3306:3306"
Yes, so i can debug what was wrong with the db.

2024-01-21 10:17 UTC, Pdzly commented on src/components/front-page-feed/index.tsx
> +  const [siteResponse] = useState<GetSiteResponse>(site);
It changes per user because in there, they saved "my_user" that indicated the current logged in user.

2024-01-21 10:26 UTC, Pdzly commented on src/components/markdown/index.tsx
> +  remarkPlugins: PluggableList | null | undefined;
i thought null !== undefined in js? I can see the undefined beeing useless but null has to be there i think

2024-01-21 10:33 UTC, Pdzly commented on src/components/sidebar-siteinfo/index.tsx
> +      <Collapsable open={adminOpen} onSwitch={setAdminOpen} title="Admins" contentClassName="flex flex-row" containerClassName="border-t border-gray-500" showIcon>
I did the containerClassName all the same because they all were the same, i would just extract it in a variable and use the variable

2024-01-21 10:35 UTC, Pdzly commented on src/components/collapsable/index.tsx
> +    if (onSwitch) {
I did that because we could use this in a "controlled" and "uncontrolled" state. Could be more reusable.

2024-01-22 00:59 UTC, kgilles commented on src/components/front-page-feed/index.tsx
> +  const [siteResponse] = useState<GetSiteResponse>(site);
Right, but the site data will never change for the same user while they're on the page. State changes are only necessary for "live" data, like the posts which need to update when the user changes a filter or sorting option.

2024-01-22 01:01 UTC, kgilles commented on src/components/markdown/index.tsx
> +  remarkPlugins: PluggableList | null | undefined;
Yes, that's correct. But for typescript the question mark just marks the prop as optional. We don't have to specify what kind of falsy values to expect if we're only looking for whether the prop is defined or not.

2024-01-22 01:08 UTC, kgilles commented on src/components/sidebar-siteinfo/index.tsx
> +      <Collapsable open={adminOpen} onSwitch={setAdminOpen} title="Admins" contentClassName="flex flex-row" containerClassName="border-t border-gray-500" showIcon>
If the classes are the same every time we use the component then it doesn't need to be a prop. It can just be part of the component styles by default. As when a component has a prop it's assumed that specific value may change on state updates or that it'll be mounted with different configurations across the app. Which isn't the case for `Collapsable`.

2024-01-22 01:10 UTC, kgilles commented on src/components/collapsable/index.tsx
> +    if (onSwitch) {
I prefer if we don't assume future use cases. If we don't end up needing both approaches then parts of this component code will be unused.

I'd rather we update components in the future when we know for sure we want more than one option.

2024-01-22 01:31 UTC, kgilles requested changes

2024-01-22 01:31 UTC, kgilles commented on src/components/post-feed-sort/index.tsx
> +        className="p-4 py-4 block md:hidden text-xs ml-4"
`p-4` includes `py-4`. We only need the first one.

2024-01-22 01:31 UTC, kgilles commented on src/components/post-feed-sort/index.tsx
> +  <ButtonGroup className="flex" placeholder={undefined}>
What's this undefined placeholder for?

2024-01-22 01:31 UTC, kgilles commented on src/utils/localstorage.ts
> +      // Workaround for that the other useEffect does not run on first render
Why do we need the ref to initially be `true` but then change it immediately to `false`?

If it's because we don't have the local storage value on first render then I vote we assume it's closed(in the sidebar scenario). Otherwise there's a bunch of flickering going on with it,

2024-01-22 23:39 UTC, kgilles requested changes
Couple of unanswered/unresolved comments left in the PR.

Also noticed that in mobile with the sidebar content expanded it won't allow me to view the entire sidebar. It stops scrolling before I reach the bottom.
![image](https://github.com/sublinks/sublinks-frontend/assets/2633655/645b6170-92b3-4c7b-835f-f00c04077caa)

2024-01-23 14:46 UTC, kgilles commented on src/app/page.tsx
> +    : JSON.stringify(testSiteData) as unknown as GetSiteResponse;
Stringifying the test data makes it unable to load without Docker because it's a string rather than an object.

`TypeError: siteResponse.site_view is undefined`

2024-01-23 16:55 UTC, Pdzly commented on src/components/post-feed-sort/index.tsx
> +  <ButtonGroup className="flex" placeholder={undefined}>
idk know the code refuseed to run, it forced me to add it.

2024-01-23 21:07 UTC, Pdzly commented
> Couple of unanswered/unresolved comments left in the PR.
> 
> Also noticed that in mobile with the sidebar content expanded it won't allow me to view the entire sidebar. It stops scrolling before I reach the bottom. ![image](https://private-user-images.githubusercontent.com/2633655/298758328-645b6170-92b3-4c7b-835f-f00c04077caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDQyOTUsIm5iZiI6MTcwNjA0Mzk5NSwicGF0aCI6Ii8yNjMzNjU1LzI5ODc1ODMyOC02NDViNjE3MC05MmIzLTRjN2ItODM1Zi1mMDBjMDQwNzdjYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMjEwNjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNkMWExODljMmJiMzg3ZGE0MDQwMjE0YjgyNDg4NDI4YmFjZDVmMDgxMGUzNmFmZTVjNzNmYTJmNzJiMzhlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iYW9nseadwUEho9vm2tCRN0BUSuzfjYShpsH0JXb2zM)

correct, you have to scroll ( the whol page ).

2024-01-23 21:28 UTC, Pdzly commented
Fixed

2024-01-23 21:31 UTC, Pdzly commented
![image](https://github.com/sublinks/sublinks-frontend/assets/34943569/4bc5811f-904e-451e-b9c9-fc223fab060f)
This is not directly work for this PR but posts are blocked by the bottom bar

2024-01-24 00:50 UTC, kgilles commented on src/components/post-feed-sort/index.tsx
> +  <ButtonGroup className="flex" placeholder={undefined}>
Did some research and found that it's an "issue" with the latest `@types/react` package. [This change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67170) removed "placeholder" from HTML elements. Material might be putting something out in the future to solve it so we can upgrade. But for now I vote we downgrade and lock `@types/react` to 18.2.42. What do you think?

2024-01-24 00:55 UTC, kgilles commented
> correct, you have to scroll ( the whol page ).

@Pdzly  I didn't even notice that the sidebar is above the feed. Not sure if I like that. I would expect it to replace the feed. As in, you can either only view the feed or only the sidebar. Be it its own page, like Reddit, or plastered on top using absolute positioning.

2024-01-24 05:07 UTC, Pdzly commented on src/components/collapsable/index.tsx
> +    if (onSwitch) {
Yeah i removed the unused part

2024-01-24 05:08 UTC, Pdzly commented on etc/dev/docker-compose.dev.yml
> +      - "3306:3306"
I just had to check if the backend would create the roles in the db correctly

2024-01-24 05:09 UTC, Pdzly commented on src/components/front-page-feed/index.tsx
> +  const [siteResponse] = useState<GetSiteResponse>(site);
Ok

2024-01-24 17:24 UTC, Pdzly commented on src/components/post-feed-sort/index.tsx
> +  <ButtonGroup className="flex" placeholder={undefined}>
yeah i dont know how

2024-01-24 17:28 UTC, Pdzly commented on src/components/post-feed-sort/index.tsx
> +  <ButtonGroup className="flex" placeholder={undefined}>
Found out ;D

2024-01-25 01:39 UTC, kgilles approved these changes

2024-01-25 16:14 UTC, merged