Improve navbar visuals
sublinks/sublinks-frontend pull request #68
Opened 2024-01-24 08:33 UTC by Ategon

Various changes to improve how the navbar looks. Implemented the mobile navbar hiding for pages with post feeds

Closes #61

2024-01-24 08:34 UTC, Ategon commented
Old vs New

![image](https://github.com/sublinks/sublinks-frontend/assets/73616169/f2fc5e6e-a5e1-4b9c-9df9-b9cb724909d4)

![image](https://github.com/sublinks/sublinks-frontend/assets/73616169/affbd864-0c5d-464e-a76b-b7197156efd1)

2024-01-25 02:17 UTC, kgilles requested changes
Looks great! Appreciate the help.

2024-01-25 02:17 UTC, kgilles commented on src/components/header/header-header.tsx
nit: This naming becomes quite confusing with three "header" in the path. Perhaps this could be named something like "layout" or "container". What do you think?

2024-01-25 02:17 UTC, kgilles commented on src/components/header/header-header.tsx
> +    } else if (window.scrollY <= 100) {
nit: No need for the condition on this line.
`} else {` alone would cover the same scenarios.

We could also simplify this function to `setMinimized(window.scrollY > 100)`.

2024-01-25 02:17 UTC, kgilles commented on src/components/header/header-link.tsx
> +  <Link href={href} className={cx('hover:scale-105 transition-scale duration-200', className)}>
After playing with it I would prefer we don't change the scale of the text when hovered.

2024-01-25 02:17 UTC, kgilles commented on src/components/header/header-logo-icon.tsx
> +  function handleScroll() {
Since we're re-using this scroll functionality, what do you think about creating a hook that manages states relevant to scroll behavior? Perhaps something we can use for both the desktop and mobile navs.

2024-01-25 02:17 UTC, kgilles commented on src/components/header/header-logo.tsx
> +    <p>{name}</p>
Please use one of out homemade text components here, or create a new one if none of the existing ones does what you want.

2024-01-25 02:17 UTC, kgilles commented on src/components/header/header-search.tsx
> +const HeaderSearch = () => (
nit: There's a massive amount of classes being added to the search field. Can any amount of them be added to a variable, and have that variable reappear for each className prop? Instead of writing them all out for each one.

2024-01-25 02:17 UTC, kgilles commented on src/components/header/index.tsx
> +        <HeaderLink href="/create_post">
Link to create post page is `/p`
For communities it'll be `/c`

2024-01-25 02:17 UTC, kgilles commented on src/components/header/index.tsx
> +          <Icon IconType={ClipboardIcon} size={ICON_SIZE.SMALL} title="Donate icon" isInteractable />
Title doesn't match icon. Also what is "registration applications"?

2024-01-25 02:17 UTC, kgilles commented on src/components/profile-menu/index.tsx
> +            <Image src="/logo.png" alt="Profile image" width={30} height={30} className="rounded-full" />
Having the site logo as the user profile picture feels confusing. I'd rather keep the user icon, unless the user has uploaded an avatar.

2024-01-25 02:37 UTC, Ategon commented on src/components/bottom-nav/bottom-nav-div.tsx
> +    const regex = /\/c\/[^/]+(?!.)/; // Community URL
Yeah probably since people will be trying to focus on the comments, I can add it in

2024-01-25 02:39 UTC, Ategon commented on src/components/header/index.tsx
> +          <Icon IconType={ClipboardIcon} size={ICON_SIZE.SMALL} title="Donate icon" isInteractable />
Registration applications are applications to join the server if the instance has applications enabled. discuss.online doesnt have it but lots of instances do such as world, p.d, beehaw, etc.

2024-01-25 02:40 UTC, Ategon commented on src/components/profile-menu/index.tsx
> +            <Image src="/logo.png" alt="Profile image" width={30} height={30} className="rounded-full" />
Yeah that was mostly meant as a placeholder until auth is added in so we can pull images. Ill make it a conditional thats always false for now

2024-01-25 03:58 UTC, Ategon commented on src/components/header/header-header.tsx
Renaming to layout makes sense, will do that

2024-01-25 04:00 UTC, Ategon commented on src/components/header/header-logo-icon.tsx
> +  function handleScroll() {
Makes sense, will add that in

2024-01-25 05:03 UTC, Ategon commented
Pushed the changes asked for above

For the inbox, reports, and registration applications I made the icons always hidden for now but when auth is added in that should change to use that to determine whether or not it shows. Same for the profile picture vs icon on the right of the header

2024-01-26 02:16 UTC, kgilles approved these changes
With the sidebar and now this PR being added we have two test data files for site/instance data. I'm approving this as what you've added works great. But if you're up for it feel free to update the app to only use one source of instance data. If not we'll just add it as a quick follow-up on the project board.

2024-01-26 04:43 UTC, Ategon commented
Updated, also fixed an issue where the banner wasnt setting width and height which errored it out and an issue with client side env variables

2024-01-26 14:34 UTC, kgilles approved these changes

2024-01-26 15:42 UTC, Pdzly approved these changes
Looks really good!

2024-01-26 22:31 UTC, merged