Prevent initial useEffect call in Feed component
sublinks/sublinks-frontend pull request #78
Opened 2024-02-06 20:28 UTC by slickplaid

Modified the Feed component to prevent the useEffect hook from running its logic on the initial component mount. Introduced a useRef hook to track the component's mount status. This change ensures that the getPosts function is only called in response to changes in postFeedSort or postFeedType, avoiding unnecessary API calls during the initial render.

https://github.com/sublinks/sublinks-frontend/issues/48

2024-02-08 00:55 UTC, kgilles requested changes
Thanks for helping out!

While testing I noticed that `useEffect` is always run twice on initial mount. Even if the dependency states don't change. And since it runs twice, the second time will always make the `getPosts` requests.

I wonder if it would help to track the initial post feed state instead, and only allow `getPosts` when either has changed from its original value. What do you think?

2024-02-08 16:06 UTC, slickplaid commented
> Thanks for helping out!
> 
> While testing I noticed that `useEffect` is always run twice on initial mount. Even if the dependency states don't change. And since it runs twice, the second time will always make the `getPosts` requests.
> 
> I wonder if it would help to track the initial post feed state instead, and only allow `getPosts` when either has changed from its original value. What do you think?

Absolutely, I can take a look at this as soon as I get the local dev environment set up. It appears the sublinks/sublinks-api docker image requires read only access to view that I don't have (even with my personal access token from my account).

If granting that access is an issue, I believe I could manually build the sublinks-api project and use the resulting docker container locally if access to the registry isn't allowed for me.

2024-03-04 18:23 UTC, slickplaid commented
For dependency states, I'm assuming you meant the `postFeedType` and `postFeedSort` values. Let me know if there are other states I should track to prevent re-loading the `getPosts()`.

2024-03-08 02:55 UTC, kgilles approved these changes

2024-03-08 03:06 UTC, merged