Feature/dark mode swithc
sublinks/sublinks-frontend pull request #8
Opened 2023-12-15 19:51 UTC by Pdzly

2023-12-16 01:16 UTC, kgilles requested changes

2023-12-16 01:16 UTC, kgilles commented on src/components/theme-switch/index.tsx
> +const darkIcon = (
Could we use the `MoonIcon` from `heroicons` here instead, to keep icons consistent?

2023-12-16 01:16 UTC, kgilles commented on src/utils/theme.ts
> +  return useLocalStorage('theme', typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
Since it's also preventing certain tailwind response threshold classes from working, it causes the bottom nav bar to overflow in narrow screens.
![image](https://github.com/sublinks/sublinks-frontend/assets/2633655/cc5ff339-12a5-4a74-bc0c-930ddb443fe1)

2023-12-16 01:16 UTC, kgilles commented on src/components/profile-menu/index.tsx
> +    <div className="flex justify-center items-center">
Please make this a `button` with an `aria-label` to make it more accessible.

2023-12-16 01:16 UTC, kgilles commented on src/components/profile-menu/index.tsx
The menu dropdown stays open after page navigation. I'd prefer it closes when a user clicks on an option that takes them to another page. What do you think?

2023-12-16 20:52 UTC, Pdzly commented on src/utils/theme.ts
> +  return useLocalStorage('theme', typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
Weirdly i dont get it. Or what do you mean it directly?

2023-12-17 14:08 UTC, Pdzly commented on src/components/theme-switch/index.tsx
> +const ThemeSwitch = ({ mode, onSwitch }: { mode: 'dark' | 'light', onSwitch: (newState: 'dark' | 'light') => void }) => (
yeah i can do that

2023-12-17 14:19 UTC, Pdzly commented on src/components/profile-menu/index.tsx
It would be annoying for the user if he changes the darkmode. And i rather like that it stays open, if you didnt wanted to go there you can click to go somewhere else.

2023-12-17 14:26 UTC, Pdzly commented on src/components/profile-menu/index.tsx
> +    <div className="flex justify-center items-center">
I would not do that to the whole menu i would do a aria label to the button and the menu

2023-12-17 16:15 UTC, kgilles requested changes

2023-12-17 16:15 UTC, kgilles commented on src/components/profile-menu/index.tsx
> +    <div className="flex justify-center items-center">
Ah, good thought. Putting it under `MenuHandler` like you did makes a lot more sense.

However, since we want it to be an invisible button it'd be easier to use the default `button` element rather than one from MT that requires us to style it to make it invisible.

2023-12-17 16:15 UTC, kgilles commented on src/components/profile-menu/index.tsx
Right we don't close it when they change modes. I was thinking about when they navigate to their profile page from the menu dropdown for example. If they use the profile menu to navigate somewhere else then they're done using it.

It's also staying open if I click to show it but then click another link on the page, like "Create post".

2023-12-17 18:11 UTC, kgilles approved these changes

2023-12-17 19:36 UTC, kgilles approved these changes

2023-12-17 19:36 UTC, merged